service: bank-slip-service

frameworkVersion: '3'

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  tracing:
    apiGateway: true
    lambda: true
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource: '*'

functions:
  find:
    handler: src/infra/handlers/find.handler
    events:
      - http:
          path: /slip/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
  create:
    handler: src/infra/handlers/create.handler
    events:
      - http:
          path: /slip/
          method: post              

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bank-slip
        AttributeDefinitions:
          - AttributeName: code
            AttributeType: S
        KeySchema:
          - AttributeName: code
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
